# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 黄亚宁的博客
subtitle: 哈哈哈哈哈
description: 随笔、日志、技术分享、个人作品
keywords: 黄亚宁, 博客, Hexo
author: 黄亚宁
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.huangyaning.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: default
theme_config:
  theme_color:
    primary: indigo
    accent: pink

  notice:

  favicon: /images/favicon.jpg
  banner: /images/banner.jpg
  avatar: /images/avatar.jpg
  rss: /atom.xml

  email: 1036616721@qq.com
  sns:
    twitter:
    facebook:
    google_plus:
    weibo:
    instagram:
    tumblr:
    github: https://github.com/yaninghuang
    linkedin:
    zhihu:
    douban:
    qq: tencent://message/?uin=1036616721&Menu=yes
    wechat:

  open_graph:
    twitter:
    google_plus:
    fb_admins:
    fb_app_id:
  site_verification:
    google:
    baidu:
  analytics:
    google_site_id:
    baidu_site_id:
    cnzz_site_id:

  pages:
  - name: 标签云
    link: /tagcloud
  - name: 画廊
    link: /gallery
  links:

  since: 2019
  footer_text:
  license: 本文遵循 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a> 许可协议

  gallery:
    fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
    fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
    jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
    lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
  busuanzi:
    site: true
    page: true
    busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  qrcode:
    caption: 发送到手机
    use: plugin
  donate:
  - name: 支付宝
    link: /images/alipay.jpg
  - name: 微信支付
    link: /images/wechat.jpg
  search:
    placeholder: 请输入关键字
    path: /search.xml
    use: plugin
  comment:
    use: gitalk
    disqus_shortname:
    gitalk_client_id: eb07933d1f72ce368a75
    gitalk_client_secret: 2e279ed3a469be2a3651ee6aef489a1850674cbd
    gitalk_repo: yaninghuang.github.io
    gitalk_owner: yaninghuang
    gitalk_sid_type: uuid
    livere_data_uid:
    valine_leancloud_app_id:
    valine_leancloud_app_key:
    valine_placeholder:
    valine_page_size:
    valine_avatar:
    valine_lang:
    valine_guest_info:
    valine_notify:
    valine_verify:
    changyan_app_id:
    changyan_app_key:
    changyan_sid_type:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:yaninghuang/yaninghuang.github.io.git
  branch: master

# Markdown
## Docs: https://github.com/niemingzhao/hexo-renderer-markdown#readme
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: “”‘’
  plugins:
    markdown-it-anchor:
      level: 1
      permalink: true
      renderPermalink: function (b,c,d,a){var f;var e=[Object.assign(new d.Token("link_open","a",1),{attrs:[["class",c.permalinkClass],["href",c.permalinkHref(b,d)],["aria-hidden",true]]}),new d.Token("link_close","a",-1)];(f=d.tokens[a+1].children)["push"].apply(f,e)}
      permalinkClass: header-anchor
      permalinkSpace: false
      permalinkSymbol: ""
      permalinkBefore: false
    markdown-it-checkbox:
      divWrap: false
      divClass: checkbox
      idPrefix: checkbox
    markdown-it-katex:
      throwOnError: false
      errorColor: "#cc0000"
      csslink: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css

# Cleanup
## Docs: https://github.com/mamboer/hexo-filter-cleanup#readme
hfc_useref:
  enable: true
  concat: true
  exclude:
hfc_html:
  enable: true
  exclude:
hfc_css:
  enable: true
  exclude:
  - "*.min.css"
hfc_js:
  enable: true
  mangle: true
  exclude:
  - "*.min.js"
hfc_img:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: false
  jpegrecompressQuality: "medium"
  optipng: true
  svgo: true
hfc_favicons:
  enable: true
  src: images/favicon.jpg
  target: images/
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false
